
  db:
    image: postgres:16.8-alpine3.20
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polling_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: 